### ISSUE TITLE
Generating schema.graphql ourt of models

### ISSUE THREAD

**Issue by hadihonarvar** [ts-graphql/ts-graphql#57]
It is not clear in the code how to generate schema.graphql file out of created models. It needs to include queries, mutations, filters, inputs, lists, node, edges, etc.

**Comment by stephentuso** [comment]
Sorry for the late reply - if you already have the schema as shown [here](https://github.com/ts-graphql/ts-graphql#schema), you could generate `schema.graphql` with a script like this:

**printSchema.ts**
```
import { schema } from './src/schema';
import { printSchema } from 'graphql';

process.stdout.write(printSchema(schema));
```
and then run:
`npx ts-node printSchema.ts > schema.graphql`

This library will be getting some updates soon. It is barebones on purpose, I'll be starting on a more batteries-included framework that uses this as a base
